# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'galop.ui'
##
## Created by: Qt User Interface Compiler version 6.1.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1448, 725)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 741, 251))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 101, 21))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label.setFont(font)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 30, 57, 14))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 30, 81, 16))
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(190, 30, 71, 16))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(330, 30, 71, 16))
        self.x_global = QLineEdit(self.frame)
        self.x_global.setObjectName(u"x_global")
        self.x_global.setGeometry(QRect(70, 50, 81, 22))
        self.x_local = QLineEdit(self.frame)
        self.x_local.setObjectName(u"x_local")
        self.x_local.setGeometry(QRect(180, 50, 81, 22))
        self.x_m = QPushButton(self.frame)
        self.x_m.setObjectName(u"x_m")
        self.x_m.setGeometry(QRect(280, 50, 41, 22))
        self.x_step = QLineEdit(self.frame)
        self.x_step.setObjectName(u"x_step")
        self.x_step.setGeometry(QRect(330, 50, 81, 22))
        self.x_p = QPushButton(self.frame)
        self.x_p.setObjectName(u"x_p")
        self.x_p.setGeometry(QRect(420, 50, 41, 22))
        self.x_acc = QLineEdit(self.frame)
        self.x_acc.setObjectName(u"x_acc")
        self.x_acc.setGeometry(QRect(480, 50, 81, 22))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(490, 30, 81, 16))
        self.x_speed = QLineEdit(self.frame)
        self.x_speed.setObjectName(u"x_speed")
        self.x_speed.setGeometry(QRect(570, 50, 101, 22))
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(580, 30, 91, 16))
        self.home = QPushButton(self.frame)
        self.home.setObjectName(u"home")
        self.home.setGeometry(QRect(580, 210, 80, 22))
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 50, 16, 16))
        self.set_origin = QPushButton(self.frame)
        self.set_origin.setObjectName(u"set_origin")
        self.set_origin.setGeometry(QRect(70, 210, 80, 22))
        self.goto_origin = QPushButton(self.frame)
        self.goto_origin.setObjectName(u"goto_origin")
        self.goto_origin.setGeometry(QRect(180, 210, 80, 22))
        self.y_acc = QLineEdit(self.frame)
        self.y_acc.setObjectName(u"y_acc")
        self.y_acc.setGeometry(QRect(480, 80, 81, 22))
        self.y_m = QPushButton(self.frame)
        self.y_m.setObjectName(u"y_m")
        self.y_m.setGeometry(QRect(280, 80, 41, 22))
        self.y_p = QPushButton(self.frame)
        self.y_p.setObjectName(u"y_p")
        self.y_p.setGeometry(QRect(420, 80, 41, 22))
        self.y_global = QLineEdit(self.frame)
        self.y_global.setObjectName(u"y_global")
        self.y_global.setGeometry(QRect(70, 80, 81, 22))
        self.y_local = QLineEdit(self.frame)
        self.y_local.setObjectName(u"y_local")
        self.y_local.setGeometry(QRect(180, 80, 81, 22))
        self.y_step = QLineEdit(self.frame)
        self.y_step.setObjectName(u"y_step")
        self.y_step.setGeometry(QRect(330, 80, 81, 22))
        self.y_speed = QLineEdit(self.frame)
        self.y_speed.setObjectName(u"y_speed")
        self.y_speed.setGeometry(QRect(570, 80, 101, 22))
        self.z_acc = QLineEdit(self.frame)
        self.z_acc.setObjectName(u"z_acc")
        self.z_acc.setGeometry(QRect(480, 110, 81, 22))
        self.z_m = QPushButton(self.frame)
        self.z_m.setObjectName(u"z_m")
        self.z_m.setGeometry(QRect(280, 110, 41, 22))
        self.z_p = QPushButton(self.frame)
        self.z_p.setObjectName(u"z_p")
        self.z_p.setGeometry(QRect(420, 110, 41, 22))
        self.z_global = QLineEdit(self.frame)
        self.z_global.setObjectName(u"z_global")
        self.z_global.setGeometry(QRect(70, 110, 81, 22))
        self.z_local = QLineEdit(self.frame)
        self.z_local.setObjectName(u"z_local")
        self.z_local.setGeometry(QRect(180, 110, 81, 22))
        self.z_step = QLineEdit(self.frame)
        self.z_step.setObjectName(u"z_step")
        self.z_step.setGeometry(QRect(330, 110, 81, 22))
        self.z_speed = QLineEdit(self.frame)
        self.z_speed.setObjectName(u"z_speed")
        self.z_speed.setGeometry(QRect(570, 110, 101, 22))
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 80, 16, 16))
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 110, 57, 14))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 270, 1211, 411))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_2 = QPushButton(self.tab)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(10, 20, 141, 22))
        self.textEdit = QTextEdit(self.tab)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 60, 141, 141))
        self.lineEdit = QLineEdit(self.tab)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(80, 230, 113, 22))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 230, 57, 14))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1448, 19))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Translation", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Axis", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Global (mm)", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Local (mm)", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Step (mm)", None))
        self.x_m.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.x_p.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Acc (mms<sup>-2</sup>)", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Speed (mm/s)", None))
        self.home.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.set_origin.setText(QCoreApplication.translate("MainWindow", u"Set Origin", None))
        self.goto_origin.setText(QCoreApplication.translate("MainWindow", u"Goto Origin", None))
        self.y_m.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.y_p.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.z_m.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.z_p.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Get Current position", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"3D scan", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"1D Scan", None))
    # retranslateUi

